### ISSUE TITLE
Can't launch any of the windows versions of rafflerunner, do any of them even work?

### ISSUE THREAD

**Issue by bruhmomentobama** [depthbomb/RaffleRunner#1]
Hi, so I ran every single windows executable from the list and none of them stayed open, idk what's wrong, is it in early alpha or beta?

**Comment by depthbomb** [comment]
Are you attempting to run it by double-clicking the executable?

**Comment by bruhmomentobama** [comment]
> 

Yes, isnt...that how this works? i also did run as admin
